version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:13.14-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sales
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yaroslav.auto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"