# Generated by Django 5.1.1 on 2024-09-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'laboratory_item',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'laboratory_order',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.laboratoryorder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.laboratoryitem')),
            ],
            options={
                'db_table': 'laboratory_order_items',
            },
        ),
    ]
