# Generated by Django 5.1.1 on 2024-10-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='laboratoryorder',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='laboratoryorderitems',
            options={'managed': False},
        ),
    ]
