# Generated by Django 5.1.1 on 2024-10-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_laboratoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laboratoryorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laboratoryorderitems',
            options={},
        ),
    ]
