# Generated by Django 5.1.1 on 2024-10-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_alter_laboratoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laboratoryitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удален'), (3, 'Сформирован'), (4, 'Завершён'), (5, 'Отклонён')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.laboratoryorder'),
        ),
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.laboratoryitem'),
        ),
        migrations.AlterUniqueTogether(
            name='laboratoryorderitems',
            unique_together={('order', 'product_id')},
        ),
    ]
