# Generated by Django 5.1.1 on 2024-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_laboratoryitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
