# Generated by Django 5.1.1 on 2024-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_laboratoryorder_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorder',
            name='accepted_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='submited_date',
            field=models.DateField(blank=True),
        ),
    ]
