# Generated by Django 5.1.1 on 2024-10-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryorder',
            options={},
        ),
    ]
