# Generated by Django 5.1.1 on 2024-10-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_alter_laboratoryorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorder',
            name='accepted_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='submited_date',
            field=models.DateField(),
        ),
    ]
