# Generated by Django 5.1.1 on 2024-10-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_alter_laboratoryorder_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryorder',
            options={'managed': False},
        ),
    ]
