# Generated by Django 5.1.1 on 2024-10-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_alter_laboratoryorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryorder',
            options={},
        ),
    ]
