# Generated by Django 5.1.1 on 2024-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_alter_laboratoryorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorder',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='submited_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
