# Generated by Django 5.1.1 on 2024-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorder',
            name='created_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
