# Generated by Django 5.1.1 on 2024-10-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laboratoryorder_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='laboratory.laboratoryorder'),
        ),
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='laboratory.laboratoryitem'),
        ),
    ]
