# Generated by Django 5.1.1 on 2024-10-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_laboratoryorderitems_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryitem',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='submited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoryorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='laboratory.authuser'),
        ),
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment', to='laboratory.laboratoryorder'),
        ),
        migrations.AlterField(
            model_name='laboratoryorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment', to='laboratory.laboratoryitem'),
        ),
    ]
